### ISSUE TITLE
issue when running as service

### ISSUE THREAD

**Issue by dgielis** [skmp/node-msoffice-pdf#1] opened 2015-08-31 17:26 UTC
Hello,

When we try to run the node module as a service (in Windows) it doesn't seem to do the conversion.
Do you have an idea what's happening or what we could try to debug the issue?

Thanks so much,
Dimitri

**Comment by skmp** [comment] 2015-08-31 19:25
Hello,
Unfortunately printing on windows doesn't work without a full session, so this will not work correctly if run as a service. You can try running the service as a full user or to "interact with desktop" (there's a setting for it)
![service-allow-interract-desktop-2015-08-31 20_11_06-services](https://cloud.githubusercontent.com/assets/393266/9586394/e8be1248-501c-11e5-9c96-f462225239e5.png)

I've had issues in the past with this trick though. The best way I think is to run it as a normal application on a different user account (so the UI doesn't show up).

Hoping to hear what works best for you!

**Comment by suniltandan** [comment] 2015-09-15 08:34
Thanks for your quick reply.
We tried what you suggested but it does not seem to be working. We have tried testing with your code:

``` javascript
var inputfile  ="C:/Work/Apex/apex-office-print/github bug report/input.docx";
var outputfile = "C:/Work/Apex/apex-office-print/github bug report/output.pdf";
var msopdf = require('node-msoffice-pdf');
msopdf(null, function(error, office) {

    if (error) {
        console.log("Init failed", error);
        return;
    }

    /*
     There is a queue on the background thread, so adding things is non-blocking.
   */

    office.word({
        input: inputfile,
        output: outputfile
    }, function(error, pdf) {
        if (error) {
            /* 
               Sometimes things go wrong, re-trying usually gets the job done
               Could not get remoting to repiably not crash on my laptop
           */
            console.log("Woops", error);
        } else {
            console.log("Saved to", pdf);
        }
    });

    office.close(null, function(error) {
        if (error) {
            console.log("Woops", error);
        } else {
            console.log("Finished & closed");
        }
    });
});


```

Running it normally using :

```
node index.js
```

gives us the result as intended:

```
Saved to C:\Work\Apex\apex-office-print\github bug report\output.pdf
Finished & closed
```

But after using nssm to create a service with Path pointing to node and Arguments index.js we get the following output from the service:

```
Woops { [System.NullReferenceException: Object reference not set to an instance of an object.]
  Message: 'Object reference not set to an instance of an object.',
  Data: {},
  InnerException: null,
  TargetSite: {},
  StackTrace: '   at Startup.<>c__DisplayClass9.<word>b__8()\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Startup.<word>d__b.MoveNext()',
  HelpLink: null,
  Source: 'oqh2sywt',
  HResult: -2147467261,
  message: 'Object reference not set to an instance of an object.',
  name: 'System.NullReferenceException' }
Finished & closed
```

Although the service outputs that it has finished and closing, the word process however seem to be running in background and starts eating up the memory until no memory is available. Actually caused a BSOD on my machine.

Since this is a reference exception, i suppose word is not finding the input file. So there might be something wrong while passing the arguments? But then again running it normally does not seem to be producing this error.
Do you have any idea what might be causing this error? or how we could debug this?

Thanks

**Comment by suniltandan** [comment] 2015-09-30 08:25
Glad to let you know that the problem has been solved.
A tweak is required to run Microsoft Office as service since Microsoft doesn't support it. 

Solution:
http://stackoverflow.com/questions/1006923/automating-office-via-windows-service-on-server-2008/1680214#1680214

**Comment by skmp** [comment] 2016-09-06 11:25
Good to see there is a workaround. Closing this :)

**Closed as completed by skmp** 2016-09-06 11:25 UTC
